
export const BALANCE_LOADED = "BALANCE_LOADED";

export const TERM_LOADED = "TERM_LOADED";

export const INCOME_CATEGORY_DATA_LOADED = "INCOME_CATEGORY_DATA_LOADED";

export const SPENDING_CATEGORY_DATA_LOADED = "SPENDING_CATEGORY_DATA_LOADED";