
export const LOADED_ERROR = "LOADED_ERROR";

export const INCOME_BALANCE_LOADED = "INCOME_BALANCE_LOADED";

export const SPENDING_BALANCE_LOADED = "SPENDING_BALANCE_LOADED";

export const TERM_LOADED = "TERM_LOADED";

export const INCOME_CATEGORY_DATA_LOADED = "INCOME_CATEGORY_DATA_LOADED";

export const SPENDING_CATEGORY_DATA_LOADED = "SPENDING_CATEGORY_DATA_LOADED";