
export const LOADED_ERROR = "LOADED_ERROR";

export const INCOME_BALANCE_LOADED = "INCOME_BALANCE_LOADED";

export const SPENDING_BALANCE_LOADED = "SPENDING_BALANCE_LOADED";

export const TERM_LOADED = "TERM_LOADED";

export const INCOME_CATEGORY_DATA_LOADED = "INCOME_CATEGORY_DATA_LOADED";

export const SPENDING_CATEGORY_DATA_LOADED = "SPENDING_CATEGORY_DATA_LOADED";

export const INCOME_CATEGORY_DATA_BY_ID = "INCOME_CATEGORY_DATA_BY_ID";

export const SPENDING_CATEGORY_DATA_BY_ID = "SPENDING_CATEGORY_DATA_BY_ID";

export const TOTAL_INCOME_AMOUNT_BY_ID = "TOTAL_INCOME_AMOUNT_BY_ID";

export const TOTAL_SPENDING_AMOUNT_BY_ID = "TOTAL_SPENDING_AMOUNT_BY_ID";

export const REMOVE_INCOME_FROM_TABLE = "REMOVE_INCOME_FROM_TABLE";

export const REMOVE_SPENDING_FROM_TABLE = "REMOVE_SPENDING_FROM_TABLE";

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};
